services:
  library_db:
    image: postgres
    container_name: library_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - library_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://library_db:5432/library_db'
      JAVA_OPTS: '-Xmx512m'