drop table if exists book;
drop table if exists person;

create table person
(
    id   int generated by default as identity primary key,
    name varchar(100) not null unique,
    year int not null
);

create table book
(
    id             int generated by default as identity primary key,
    name           varchar(100) not null,
    author         varchar(100) not null,
    year           int not null,
    person_id      int references person (id) on delete set null,
    take_book_date timestamp null
);

INSERT INTO person(name, year)
VALUES ('Kate Blanchett', 1969),
       ('Kevin Costner', 1955),
       ('Jim Carrey', 1962),
       ('Emma Watson', 1990),
       ('Bred Pitt', 1963);

INSERT INTO book(name, author, year)
VALUES ('Evening in Byzantium', 'Irwin Shaw', 1973),
       ('Martin Eden', 'Jack London', 1909),
       ('An American Tragedy', 'Theodore Dreiser', 1925),
       ('The Grapes of Wrath', 'John Steinbeck', 1939),
       ('Of Human Bondage', 'Somerset Maugham', 1915);